[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
sqlx = "0.8.0"
sqlx-cli = "0.8.0"
tokio = "1.39.3"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
